In [59]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.6'

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [13]:
df.shape[0]

10000

In [21]:
df.fuel_type.nunique()

3

In [23]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [30]:
df[df.origin == "Asia"].fuel_efficiency_mpg.max()

np.float64(41.2)

In [32]:
df.horsepower.median()

np.float64(254.0)

In [43]:
most_frequent = df.horsepower.value_counts().head(1)
most_frequent

horsepower
252.0    174
Name: count, dtype: int64

In [45]:
df.horsepower.fillna(most_frequent).median()

np.float64(254.0)

In [76]:
x = df[df.origin == "Asia"][["vehicle_weight","model_year"]].head(7).values

In [82]:
xt = x.T

In [118]:
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [109]:
xt

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [96]:
xtx = xt.dot(x)

In [111]:
xtx

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [112]:
xtx_inv = np.linalg.inv(xtx)

In [113]:
xtx_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [114]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [115]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [120]:
w = xtx_inv.dot(xt).dot(y)

In [121]:
w.sum()

np.float64(0.36919696904925486)